---
- hosts: tc
  remote_user: jenkins
  become: yes
  become_method: sudo
  tasks:
  - name: create directory cinema
    command: mkdir -p ~/cinema/
  - git:
      repo: 'https://github.com/samuelveldhuizen/cinema.git'
      dest: /home/jenkins/cinema/
      force: yes

  - name: move to directory
    command: cd /home/jenkins/cinema/Dockerfile

  - name: build docker image
    command: docker build -t test/test1 .
  
  - name: run docker container
    command: docker run -d -p 8181:8181 -v /home/sam/.m2:/home/docker/.m2  -v /home/jenkins/cinema:/tmp test/test1
