---
- hosts: tc
  remote_user: sam
  become: yes
  become_method: sudo
  tasks:
  - name: create directory cinema
    command: mkdir -p ~/cinema/
  - git:
      repo: 'https://github.com/samuelveldhuizen/cinema.git'
      dest: /home/jenkins/cinema/
      force: yes

  - name: move to directory
    command: cd /home/jenkins/cinema/Dockerfiles/

  - name: build docker image
    command: docker build -t test/test1 /home/jenkins/cinema/Dockerfiles/
  
  - name: run docker container
    command: docker run --name tomcat -d -p 8282:8181 -v /home/sam/.m2:/home/docker/.m2  -v /home/jenkins/cinema:/tmp test/test1

  - name: start docker tomcat
    command: docker start tomcat
