---
- hosts: tc
  remote_user: jenkins
  become: yes
  become_method: sudo
  tasks:
  - git:
      repo: 'https://github.com/samuelveldhuizen/cinema.git'
      dest: /home/sam/cinema/

  - name: move to directory
    command: /home/sam/cinema/

  - name: start tomcat
    command: mvn clean tomcat7:run
